### ISSUE TITLE
_PARTITIONTIME does not support partitioned table with Date datatype

### ISSUE THREAD

**Issue by NUSTemple** [doitintl/bigquery-grafana#327] opened 2021-04-25 06:30 UTC
## Bug Report
_PARTITIONTIME does not support partitioned table with Date datatype. "Could not cast literal "2021-04-19 00:00:00" to type DATE at [8:26]"

## Expected Behavior
if my partitioned data type is date, the query will change the filter to date instead of datetime. for example I have one column "create_date" is my partition

  creation_date >= DATE '2021-04-19 00:00:00' AND
  creation_date < DATE '2021-04-25 23:59:59'

## Actual Behavior
In the SQL sent to BIgQuery, 
  creation_date >= '2021-04-19 00:00:00' AND
  creation_date < '2021-04-25 23:59:59'
This will cause the bigquery error. 

## Steps to Reproduce the Problem

1. Use 1 table with DATE as partition
2. Use any metric to create the dashboarding. 

## Specifications

- Version:
- Platform: Docker
- Grafana Version: 6.5

**Comment by ofir5300** [comment] 2021-09-19 12:51
Duplicate of https://github.com/doitintl/bigquery-grafana/issues/334 which connected to an open PR

**Closed by ofir5300** 2021-09-19 12:51 UTC
Labels: duplicate
